server:
  port: 2021
spring:
  datasource:
    username: root
    password: 123456qwe
    url: jdbc:mysql://162.14.66.55:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
# redis
  redis:
    host: localhost
    port: 6379
#mybatis
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml

aliyun:
  refresh-token: cf3fb25ab4294943a2e09023ad8efab1
